### ISSUE TITLE
skin 函数返回值的潜在问题？

### ISSUE THREAD

**Issue by TTsdzb** [ahdg6/koishi-plugin-minecraft#5]
`api.ts` 26 行的 `view` 属性是指皮肤的正视图吗？`https://minotar.net/skin/<user>` 和 `https://minotar.net/download/<user>` 都是返回皮肤图片文件，只是一个在浏览器中打开，另一个直接下载。

如果要获取正视图，需要使用这个 API：

```
# 单层皮肤
https://minotar.net/body/<user>
# width 指定图像宽度
https://minotar.net/body/<user>/<width>.png

# 双层皮肤
https://minotar.net/armor/body/<user>
# width 指定图像宽度
https://minotar.net/armor/body/<user>/<width>.png
```

`api.ts` 26行：

```diff
- view: `${skinurl}/skin/${username}`,
+ view: `${skinurl}/armor/body/${username}`,
```

**Comment by ahdg6** [comment]
我看看能不能实现本地渲染，那样直接不用第三方服务还稳定点

**Comment by TTsdzb** [comment]
确实，但除非找到好的轮子，否则只会变得更麻烦

**Comment by ahdg6** [comment]
事实证明不可行，大部分都是用 three.js 或者 canvas，如果要实现本地渲染插件大小会爆棚 20MB 以上（
