### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by Starrain08** [ahdg6/koishi-plugin-minecraft#9]
使用ncqq作为登录框架时，图片无法发送，nc报错
![image](https://github.com/Kokoro-js/koishi-plugin-minecraft/assets/119772101/2a29ed9d-870f-46b3-a1b8-69074a599426)

**Comment by ahdg6** [comment]
没用过ncqq，onebot没问题，建议先排查是不是主机能不能连接到那个地址

**Comment by Starrain08** [comment]
> 没用过ncqq，onebot没问题，建议先排查是不是主机能不能连接到那个地址

主机能连接

**Comment by ahdg6** [comment]
那就是适配器请求的时候不带 UA，被服务器提供者拦下来了

**Comment by ahdg6** [comment]
转自 surgeplay 官网
`如果您的 Visage 客户端未使用自定义 UA，则所有对 Visage 的请求现在都将失败，并显示 400错误 ，返回简短的解释文本。 您必须确保使用合理的用户代理 所有向 Visage 发出的请求中的标头，最好包括指向您的网站和电子邮件的链接 如果您滥用 Visage，则需要联系您的地址。 此类 UA 的示例 是 MyProgramName/2.0 (+https://my.website/myprogramname.html; <me@my.website>). `

**Comment by Starrain08** [comment]
> 转自 surgeplay 官网 `如果您的 Visage 客户端未使用自定义 UA，则所有对 Visage 的请求现在都将失败，并显示 400错误 ，返回简短的解释文本。 您必须确保使用合理的用户代理 所有向 Visage 发出的请求中的标头，最好包括指向您的网站和电子邮件的链接 如果您滥用 Visage，则需要联系您的地址。 此类 UA 的示例 是 MyProgramName/2.0 (+https://my.website/myprogramname.html; <me@my.website>). `

NC这边作者建议是将资源下载到本地，再传到协议端

**Comment by Starrain08** [comment]
他们无法处理这个问题

**Comment by ahdg6** [comment]
说的是下载到本地的时候要带 UA

**Comment by Starrain08** [comment]
> 说的是下载到本地的时候要带 UA

他们具体给出的是插件下载缓存图片，然后转码推给协议端发送

**Comment by ahdg6** [comment]
我一直在说 UA 的问题你一直跟我讲他们怎么实现的是吧，能不能好好查一下他们的请求到底有没有 UA

**Comment by Starrain08** [comment]
> 我一直在说 UA 的问题你一直跟我讲他们怎么实现的是吧，能不能好好查一下他们的请求到底有没有 UA

已经解决，确实是框架问题，框架没有传出ua
